name: E-Health
favicon: null
layout_spectrum: 0.26946
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#08070a'
    - '#bac1cf'
    - '#6a85a1'
    - '#7bfef8'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
